//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payroll {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Payroll.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ação.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adicionar.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recursos Humanos.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem certeza que deseja remover.
        /// </summary>
        public static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esqueceu sua senha?.
        /// </summary>
        public static string AskForgotPassword {
            get {
                return ResourceManager.GetString("AskForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltar.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastros Básicos.
        /// </summary>
        public static string BasicCRUD {
            get {
                return ResourceManager.GetString("BasicCRUD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar Senha.
        /// </summary>
        public static string ChangePasswordTitle {
            get {
                return ResourceManager.GetString("ChangePasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altere as informações do seu perfil.
        /// </summary>
        public static string ChangeSettingsTitle {
            get {
                return ResourceManager.GetString("ChangeSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cidade.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limpar.
        /// </summary>
        public static string ClearFilter {
            get {
                return ResourceManager.GetString("ClearFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cores.
        /// </summary>
        public static string Colors {
            get {
                return ResourceManager.GetString("Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de Empresas.
        /// </summary>
        public static string CompaniesTitle {
            get {
                return ResourceManager.GetString("CompaniesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empresa.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha e confirmar senha não conferem.
        /// </summary>
        public static string ComparePasswordsInvalidMessage {
            get {
                return ResourceManager.GetString("ComparePasswordsInvalidMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar nova senha.
        /// </summary>
        public static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar Senha.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senhas não conferem..
        /// </summary>
        public static string ConfirmPasswordErrorMessage {
            get {
                return ResourceManager.GetString("ConfirmPasswordErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome do órgão de classe.
        /// </summary>
        public static string CouncilName {
            get {
                return ResourceManager.GetString("CouncilName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criado em.
        /// </summary>
        public static string CreatedAt {
            get {
                return ResourceManager.GetString("CreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criado por.
        /// </summary>
        public static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro adicionado com sucesso..
        /// </summary>
        public static string CreatedSuccessfully {
            get {
                return ResourceManager.GetString("CreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criar nova conta..
        /// </summary>
        public static string CreateNewAccount {
            get {
                return ResourceManager.GetString("CreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moeda.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de Moedas.
        /// </summary>
        public static string CurrencyTitle {
            get {
                return ResourceManager.GetString("CurrencyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to danger.
        /// </summary>
        public static string DangerMessageType {
            get {
                return ResourceManager.GetString("DangerMessageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remover.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removido.
        /// </summary>
        public static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removido Em.
        /// </summary>
        public static string DeletedAt {
            get {
                return ResourceManager.GetString("DeletedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removido Por.
        /// </summary>
        public static string DeletedBy {
            get {
                return ResourceManager.GetString("DeletedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detalhes.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exibindo:.
        /// </summary>
        public static string Displaying {
            get {
                return ResourceManager.GetString("Displaying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite o seu email..
        /// </summary>
        public static string EnterYourEmail {
            get {
                return ResourceManager.GetString("EnterYourEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Câmbio.
        /// </summary>
        public static string Exchange {
            get {
                return ResourceManager.GetString("Exchange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxa de câmbio obrigatória..
        /// </summary>
        public static string ExchangeRequired {
            get {
                return ResourceManager.GetString("ExchangeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisar por.
        /// </summary>
        public static string ExecuteSearch {
            get {
                return ResourceManager.GetString("ExecuteSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primeiro.
        /// </summary>
        public static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esqueci minha senha..
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por favor clique no link para resetar a sua senha: &lt;a href=&apos;{0}&apos;&gt;Aqui &lt;/a&gt;..
        /// </summary>
        public static string ForgotPasswordEmailBody {
            get {
                return ResourceManager.GetString("ForgotPasswordEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data de Criação.
        /// </summary>
        public static string FoundationDate {
            get {
                return ResourceManager.GetString("FoundationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Função.
        /// </summary>
        public static string Function {
            get {
                return ResourceManager.GetString("Function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de Funções.
        /// </summary>
        public static string FunctionsTitle {
            get {
                return ResourceManager.GetString("FunctionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Possui Conselho?.
        /// </summary>
        public static string HasCouncil {
            get {
                return ResourceManager.GetString("HasCouncil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem periculosidade?.
        /// </summary>
        public static string HasDangeroues {
            get {
                return ResourceManager.GetString("HasDangeroues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contrata Estrangeiros?.
        /// </summary>
        public static string HasStrangers {
            get {
                return ResourceManager.GetString("HasStrangers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tem insalubridade?.
        /// </summary>
        public static string HasUnhealthy {
            get {
                return ResourceManager.GetString("HasUnhealthy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Olá.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to info.
        /// </summary>
        public static string InfoMessageType {
            get {
                return ResourceManager.GetString("InfoMessageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausência.
        /// </summary>
        public static string IsAbsence {
            get {
                return ResourceManager.GetString("IsAbsence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É uma função de gerência?.
        /// </summary>
        public static string IsManagerFunction {
            get {
                return ResourceManager.GetString("IsManagerFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to items.
        /// </summary>
        public static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cargo.
        /// </summary>
        public static string JobRole {
            get {
                return ResourceManager.GetString("JobRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de Cargos.
        /// </summary>
        public static string JobRoleTitle {
            get {
                return ResourceManager.GetString("JobRoleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Último.
        /// </summary>
        public static string Last {
            get {
                return ResourceManager.GetString("Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Licença.
        /// </summary>
        public static string LicenseType {
            get {
                return ResourceManager.GetString("LicenseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de Tipo de Licença.
        /// </summary>
        public static string LicenseTypeTitle {
            get {
                return ResourceManager.GetString("LicenseTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrar.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faça login ou registre uma nova conta..
        /// </summary>
        public static string LoginMessage {
            get {
                return ResourceManager.GetString("LoginMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sair.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerencie o seu perfil.
        /// </summary>
        public static string ManagerAccountTitle {
            get {
                return ResourceManager.GetString("ManagerAccountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comissão de Gestão.
        /// </summary>
        public static string ManagerCommission {
            get {
                return ResourceManager.GetString("ManagerCommission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        public static string NA {
            get {
                return ResourceManager.GetString("NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nacionalidade.
        /// </summary>
        public static string Nacionality {
            get {
                return ResourceManager.GetString("Nacionality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string NameLabel {
            get {
                return ResourceManager.GetString("NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bairro.
        /// </summary>
        public static string Neighborhood {
            get {
                return ResourceManager.GetString("Neighborhood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova Empresa.
        /// </summary>
        public static string NewCompany {
            get {
                return ResourceManager.GetString("NewCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova Moeda.
        /// </summary>
        public static string NewCurrency {
            get {
                return ResourceManager.GetString("NewCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova Função.
        /// </summary>
        public static string NewFunction {
            get {
                return ResourceManager.GetString("NewFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo Cargo.
        /// </summary>
        public static string NewJobRole {
            get {
                return ResourceManager.GetString("NewJobRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo Tipo de Licença.
        /// </summary>
        public static string NewLicenceType {
            get {
                return ResourceManager.GetString("NewLicenceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova Profissão.
        /// </summary>
        public static string NewOccupation {
            get {
                return ResourceManager.GetString("NewOccupation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo tipo de ocorrência.
        /// </summary>
        public static string NewOccurrenceType {
            get {
                return ResourceManager.GetString("NewOccurrenceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nova Senha.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo Usuário.
        /// </summary>
        public static string NewUser {
            get {
                return ResourceManager.GetString("NewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo Local de Trabalho.
        /// </summary>
        public static string NewWorkplace {
            get {
                return ResourceManager.GetString("NewWorkplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Próximo.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum item encontrado..
        /// </summary>
        public static string NoItems {
            get {
                return ResourceManager.GetString("NoItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profissão.
        /// </summary>
        public static string Occupation {
            get {
                return ResourceManager.GetString("Occupation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Área de Atuação.
        /// </summary>
        public static string OccupationArea {
            get {
                return ResourceManager.GetString("OccupationArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de Profissões.
        /// </summary>
        public static string OccupationsTitle {
            get {
                return ResourceManager.GetString("OccupationsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Ocorrência.
        /// </summary>
        public static string OccurrenceType {
            get {
                return ResourceManager.GetString("OccurrenceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de Tipo de Ocorrências.
        /// </summary>
        public static string OccurrenceTypeTitle {
            get {
                return ResourceManager.GetString("OccurrenceTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha inválida..
        /// </summary>
        public static string PasswordLengthErrorMessage {
            get {
                return ResourceManager.GetString("PasswordLengthErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CNPJ.
        /// </summary>
        public static string PersonalJuridicalName {
            get {
                return ResourceManager.GetString("PersonalJuridicalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anterior.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perfil.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar Perfil.
        /// </summary>
        public static string ProfileTitle {
            get {
                return ResourceManager.GetString("ProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantidade padrão de dias.
        /// </summary>
        public static string QtyDaysDefault {
            get {
                return ResourceManager.GetString("QtyDaysDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrar.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lembrar-me.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remover.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro removido com sucesso..
        /// </summary>
        public static string RemovedSuccessfully {
            get {
                return ResourceManager.GetString("RemovedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo Obrigatório..
        /// </summary>
        public static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salário.
        /// </summary>
        public static string Salary {
            get {
                return ResourceManager.GetString("Salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buscar.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviar.
        /// </summary>
        public static string SendEmail {
            get {
                return ResourceManager.GetString("SendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Razão Social.
        /// </summary>
        public static string SocialReason {
            get {
                return ResourceManager.GetString("SocialReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to success.
        /// </summary>
        public static string SuccessMessageType {
            get {
                return ResourceManager.GetString("SuccessMessageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Símbolo.
        /// </summary>
        public static string Symbol {
            get {
                return ResourceManager.GetString("Symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tema.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterado em.
        /// </summary>
        public static string UpdatedAt {
            get {
                return ResourceManager.GetString("UpdatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterado por.
        /// </summary>
        public static string UpdatedBy {
            get {
                return ResourceManager.GetString("UpdatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro alterado com sucesso..
        /// </summary>
        public static string UpdatedSuccessfully {
            get {
                return ResourceManager.GetString("UpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alterar Senha.
        /// </summary>
        public static string UpdatePassword {
            get {
                return ResourceManager.GetString("UpdatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome de usuário.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to warning.
        /// </summary>
        public static string WarningMessageType {
            get {
                return ResourceManager.GetString("WarningMessageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local de Trabalho.
        /// </summary>
        public static string Workplace {
            get {
                return ResourceManager.GetString("Workplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastro de Local de Trabalho.
        /// </summary>
        public static string WorkplaceTitle {
            get {
                return ResourceManager.GetString("WorkplaceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
